using System.Collections;
using System.Text;

namespace Assets.Planner
{
    /// <summary>
    /// A completed plan generated by the planner
    /// </summary>
    public class Plan
    {
        /// <summary>
        /// Actions in the plan, in order
        /// </summary>
        public readonly Action[] Actions;

        public Plan(Action[] actions)
        {
            Actions = actions;
        }

        /// <summary>
        /// Return a coroutine (IEnumerator) that can run the actions in the plan
        /// on behalf of the specified agent.
        /// </summary>
        public IEnumerator Perform(Agent agent)
        {
            foreach (var action in Actions)
                yield return action.Implementation(agent);
        }

        public override string ToString()
        {
            var b = new StringBuilder();
            b.Append("{ ");
            foreach (var action in Actions)
            {
                b.Append(action.Name);
                b.Append(" ");
            }

            b.Append("}");
            return b.ToString();
        }
    }
}
